add a new test harness

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,39 +1,114 @@
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
 language: c
 sudo: false
 
+cache:
+  directories:
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
+    - $HOME/.stack
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+
 matrix:
   include:
-    - env: CABALVER=1.16 GHCVER=7.4.2 GHCOPTS="-Werror" JOPTS="" HAPPYOPTS=""
-      addons: {apt: {packages: [cabal-install-1.16, ghc-7.4.2], sources: [hvr-ghc]}}
-    - env: CABALVER=1.18 GHCVER=7.6.3 GHCOPTS="-Werror" JOPTS="-j2" HAPPYOPTS=""
-      addons: {apt: {packages: [cabal-install-1.18, ghc-7.6.3], sources: [hvr-ghc]}}
-    - env: CABALVER=1.18 GHCVER=7.8.4 GHCOPTS="-Werror" JOPTS="-j2" HAPPYOPTS="--constraint='transformers\ ==\ 0.3.0.0'"
-      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
-    - env: CABALVER=1.22 GHCVER=7.10.1 GHCOPTS="" JOPTS="-j2" HAPPYOPTS="--constraint='transformers\ installed'"
-      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.1],sources: [hvr-ghc]}}
-    - env: CABALVER=head GHCVER=head GHCOPTS="" JOPTS="-j2" HAPPYOPTS="--constraint='transformers\ installed'"
-      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
+    - env: CABALVER=1.16 GHCVER=7.6.3 BUILD=cabal
+      compiler: ": #GHC 7.6.3"
+      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
 
-  allow_failures:
-   - env: CABALVER=head GHCVER=head GHCOPTS="" JOPTS="-j2" HAPPYOPTS="--constraint='transformers\ installed'"
+    - env: CABALVER=1.18 GHCVER=7.8.4 BUILD=cabal
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: BUILD=stack STACK_YAML=stack-7.8.yaml STACK_OPTIONS=--skip-ghc-check
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: BUILD=stack STACK_YAML=stack-7.8.yaml
+      os: osx
+
+    - env: CABALVER=1.22 GHCVER=7.10.1 BUILD=cabal
+      compiler: ": #GHC 7.10.1"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.22 GHCVER=7.10.2 BUILD=cabal
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: BUILD=stack STACK_YAML=stack-7.10.yaml STACK_OPTIONS=--skip-ghc-check
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: BUILD=stack STACK_YAML=stack-7.10.yaml
+      os: osx
+
 
 before_install:
- - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - export CABAL=cabal-$CABALVER
- - $CABAL --version
- - travis_retry $CABAL update
-
+ - unset CC
+ - case "$BUILD" in
+     stack)
+       export STACK_VERSION=0.1.3.0;
+       export PATH=~/bin:$PATH;
+       mkdir -p ~/bin;
+       travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/stack-$STACK_VERSION-x86_64-$TRAVIS_OS_NAME.gz | gunzip > ~/bin/stack;
+       chmod a+x ~/bin/stack;
+       scripts/travis_long stack --no-terminal setup;;
+     cabal)
+       export HAPPYVER=1.19.5
+       export ALEXVER=3.1.4
+       export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH;;
+   esac
 install:
- - $CABAL install $HAPPYOPTS happy alex
- - $CABAL install $JOPTS --enable-tests --only-dependencies
+ - case "$BUILD" in
+     stack)
+       scripts/travis_long stack --no-terminal $STACK_OPTIONS build --only-snapshot -j2;;
+     cabal)
+       echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+       cabal --version;
+       if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+       then
+         zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+              $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+       fi;
+       travis_retry cabal update;
+       cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt;
+       sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt;
+       if diff -u installplan.txt $HOME/.cabsnap/installplan.txt; then
+         echo "cabal build-cache HIT";
+         rm -rfv .ghc;
+         cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+         cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+       else
+         echo "cabal build-cache MISS";
+         rm -rf $HOME/.cabsnap;
+         mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+         cabal install --only-dependencies --enable-tests --enable-benchmarks;
+         if [ "$GHCVER" = "7.10.1" ]; then cabal install Cabal-1.22.4.0; fi;
+       fi;
+       if [ ! -d $HOME/.cabsnap ]; then
+         echo "snapshotting package-db to build-cache";
+         mkdir $HOME/.cabsnap;
+         cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+         cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+       fi;;
+   esac
 
+# snapshot package-db on cache miss
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
- - $CABAL configure -v2 --enable-tests
- - $CABAL build $JOPTS --ghc-options=$GHCOPTS
- - |
-   if [ $GHCVER != "head" ]; then
-     $CABAL test
-   fi
+ - case "$BUILD" in
+     stack)
+       scripts/travis_long stack --no-terminal $STACK_OPTIONS build -j2;;
+     cabal)
+       cabal configure --enable-tests -v2;
+       cabal build;
+       cabal test;
+       cabal bench || true;
+       cabal sdist || true;
+       SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install --force-reinstalls "$SRC_TGZ");;
+   esac
 
 notifications:
   irc:
@@ -42,3 +117,4 @@ notifications:
     skip_join: true
     template:
       - "\x0313folds\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
+# EOF
